---
name: Copy Images
on:
  workflow_dispatch:

env:
  IMAGE_NAME: cop-nginx
  IMAGE_REPO: quay.io/ukhomeofficedigital

jobs:
  get_datetime:
    runs-on: ubuntu-latest
    outputs:
      datetime: ${{ steps.datetime.outputs.now }}

    steps:
      - id: datetime
        run: echo "::set-output name=now::$(date +%Y%m%d%H%M)"

  copy_to_quay:
    name: Copy Image to Quay
    runs-on: ubuntu-latest
    needs: get_datetime
    strategy:
      matrix:
        tag: ['alpine']

    steps:
      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Copy with Skopeo
        run: |
          skopeo --version
          echo "Got date ${{ needs.get_datetime.outputs.datetime }}"
          echo "Got tag ${{ matrix.tag }}"
